menu:
  Home: /
  Archives: /archives

sidebar: right

widgets:
- search
- category
- recent_posts
- tag
- tagcloud
- links


# Duoshuo
duoshuo_shortname: jiezj

fancybox: true

google_analytics:
rss: 
google_site_verification: 
baidu_site_verification: 
icon: 

# Links
links:
  tommyZZM: http://www.chalet581.xyz
  sineyuan: http://sineyuan.github.io